const router = require("express").Router()
const auth = require("../app/middleware/auth")
const userController =  require("../app/controller/user.controller")
router.post("/register", userController.register)
router.get("/all", userController.all)
router.get("/all/:id", userController.single)
router.delete("/all/:id", userController.deleteUser)
router.patch("/all/:id", userController.editUser)
router.patch("/all/editPass/:id", userController.editPass)
router.post("/login", userController.login)
router.post("/me", auth, userController.me)
router.post("/logout", auth, userController.logout)
router.post("/logoutAll", auth, userController.logoutAll)
module.exports = router